services:
  # Veritabanı: Kullanıcı ve log verilerini saklar
  postgres:
    image: postgres:18-alpine
    container_name: nac_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Veri Kalıcılığı için Konteyner silinse bile veritabanının korunmasını sağlar.
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Otomatik Başlatma: Veritabanı ilk açıldığında tabloları init.sql'den otomatik oluşturur.
    networks:
      - nac_network
    healthcheck: #API'nin veritabanı hazır olmadan bağlanmaya çalışmasını engeller.
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Önbellek: Aktif oturum takibi ve Rate-Limiting için yüksek performanslı depolama.
  redis:
    image: redis:8-alpine
    container_name: nac_redis
    command: redis-server --requirepass ${REDIS_PASSWORD} # Güvenlik için şifreli erişim.
    networks:
      - nac_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Policy Engine: RADIUS kararlarını veren merkezi FastAPI uygulaması
  api:
    build: ./api
    container_name: nac_api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on: #Bağımlılık Yönetimi: DB ve Redis tamamen 'Healthy' olmadan API başlamaz.
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - nac_network
    ports:
      - "8000:8000" # İzleme endpoints'lerine dışarıdan erişim sağlar.
    # API'nin hazır olduğunu dökümantasyon sayfasına bakarak kontrol eder
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request; urllib.request.urlopen(\"http://localhost:8000/docs\")'"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Ağ erişim isteklerini karşılayan sunucu
  freeradius:
    build: ./freeradius
    container_name: nac_freeradius
    #  API 'healthy' olana kadar RADIUS beklemede kalır
    depends_on:
      api:
        condition: service_healthy
    #  Bir hata olursa otomatik 5 kez yeniden dener
    restart: on-failure:5
    networks:
      - nac_network
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"

networks:
  nac_network: #İzole Ağ: Servislerin sadece kendi içinde konuşmasını sağlar.
    driver: bridge

volumes:
  postgres_data: # Veritabanı verilerinin saklandığı fiziksel alan.